version: "3"
services:
  node-docker-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=5000
    env_file:
      - ./.env